const data = [
  {
    id: 1,
    category: "category1-laptop",
    name: "HP corei3",
    price: 41990,
    imageSrc: "images/laptop1.jpeg",
    quantityInCart: 0,
  },
  {
    id: 11,
    category: "category1-laptop",
    name: "ASUS ROG",
    price: 78990,
    imageSrc: "images/laptop2.jpeg",
    quantityInCart: 0,
  },
  {
    id: 12,
    category: "category1-laptop",
    name: "HP Ryzen3",
    price: 39990,
    imageSrc: "images/laptop3.jpeg",
    quantityInCart: 0,
  },
  {
    id: 13,
    category: "category1-laptop",
    name: "ACER Aspire7",
    price: 52990,
    imageSrc: "images/laptop4.jpeg",
    quantityInCart: 0,
  },
  {
    id: 14,
    category: "category1-laptop",
    name: "ASUS Vivobook",
    price: 38990,
    imageSrc: "images/laptop5.jpeg",
    quantityInCart: 0,
  },
  {
    id: 15,
    category: "category1-laptop",
    name: "DELL Vostro",
    price: 40990,
    imageSrc: "images/laptop6.jpeg",
    quantityInCart: 0,
  },
  {
    id: 16,
    category: "category1-laptop",
    name: "HP corei3",
    price: 41990,
    imageSrc: "images/laptop7.jpeg",
    quantityInCart: 0,
  },
  {
    id: 17,
    category: "category1-laptop",
    name: "APPLE Macbook",
    price: 85990,
    imageSrc: "images/laptop8.jpeg",
    quantityInCart: 0,
  },
  {
    id: 18,
    category: "category1-laptop",
    name: "ACER Aspire7",
    price: 55990,
    imageSrc: "images/laptop9.jpeg",
    quantityInCart: 0,
  },
  {
    id: 19,
    category: "category1-laptop",
    name: "ASUS corei3",
    price: 33990,
    imageSrc: "images/laptop10.jpeg",
    quantityInCart: 0,
  },
  {
    id: 2,
    category: "category2-mobile",
    name: "APPLE iPhone 13",
    price: 159900,
    imageSrc: "images/mobile1.jpeg",
    quantityInCart: 0,
  },
  {
    id: 21,
    category: "category2-mobile",
    name: "SAMSUNG Z Fold3",
    price: 157999,
    imageSrc: "images/mobile2.jpeg",
    quantityInCart: 0,
  },
  {
    id: 22,
    category: "category2-mobile",
    name: "SAMSUNG Z Flip3",
    price: 84999,
    imageSrc: "images/mobile3.jpeg",
    quantityInCart: 0,
  },
  {
    id: 23,
    category: "category2-mobile",
    name: "REALME Narzo 50A",
    price: 12499,
    imageSrc: "images/mobile4.jpeg",
    quantityInCart: 0,
  },
  {
    id: 24,
    category: "category2-mobile",
    name: "NOKIA 8.1",
    price: 28999,
    imageSrc: "images/mobile5.jpeg",
    quantityInCart: 0,
  },
  {
    id: 25,
    category: "category2-mobile",
    name: "SAMSUNG F62",
    price: 25999,
    imageSrc: "images/mobile6.jpeg",
    quantityInCart: 0,
  },
  {
    id: 26,
    category: "category2-mobile",
    name: "REALME 8pro",
    price: 19999,
    imageSrc: "images/mobile7.jpeg",
    quantityInCart: 0,
  },
  {
    id: 27,
    category: "category2-mobile",
    name: "Mi 11X pro",
    price: 34900,
    imageSrc: "images/mobile8.jpeg",
    quantityInCart: 0,
  },
  {
    id: 28,
    category: "category2-mobile",
    name: "OPPO Reno6 pro",
    price: 41990,
    imageSrc: "images/mobile9.jpeg",
    quantityInCart: 0,
  },
  {
    id: 29,
    category: "category2-mobile",
    name: "ONEPLUS 9R",
    price: 43999,
    imageSrc: "images/mobile10.jpg",
    quantityInCart: 0,
  },
  {
    id: 3,
    category: "category3-camera",
    name: "CANON EOS 1500D",
    price: 36999,
    imageSrc: "images/camera1.jpg",
    quantityInCart: 0,
  },
  {
    id: 31,
    category: "category3-camera",
    name: "TECHKING action",
    price: 1599,
    imageSrc: "images/camera2.jpeg",
    quantityInCart: 0,
  },
  {
    id: 32,
    category: "category3-camera",
    name: "SJCAM 4000 air",
    price: 4999,
    imageSrc: "images/camera3.jpeg",
    quantityInCart: 0,
  },
  {
    id: 33,
    category: "category3-camera",
    name: "FUJIFILM X10",
    price: 89999,
    imageSrc: "images/camera4.jpeg",
    quantityInCart: 0,
  },
  {
    id: 34,
    category: "category3-camera",
    name: "GoPro Hero9",
    price: 36999,
    imageSrc: "images/camera5.jpeg",
    quantityInCart: 0,
  },
  {
    id: 35,
    category: "category3-camera",
    name: "PAROXYSM Mini",
    price: 784,
    imageSrc: "images/camera6.jpeg",
    quantityInCart: 0,
  },
  {
    id: 36,
    category: "category3-camera",
    name: "FUJIFILM instax",
    price: 6099,
    imageSrc: "images/camera7.jpeg",
    quantityInCart: 0,
  },
  {
    id: 37,
    category: "category3-camera",
    name: "NIKON Z FC",
    price: 96495,
    imageSrc: "images/camera8.jpeg",
    quantityInCart: 0,
  },
  {
    id: 38,
    category: "category3-camera",
    name: "F Smartbuy D68AV",
    price: 6999,
    imageSrc: "images/camera9.jpeg",
    quantityInCart: 0,
  },
  {
    id: 39,
    category: "category3-camera",
    name: "IC Plus 6",
    price: 999,
    imageSrc: "images/camera10.jpeg",
    quantityInCart: 0,
  },
];

// export default data;
